const SIGN_UP_BONUS = 'signUpBonus';
const REGISTRATION_VERIFIED_FROM_REFERRAL = 'registrationVerifiedFromReferral';
const TRIAL_TAKEN_FROM_REFERRAL = 'trialTakenFromReferral';
const COURSE_PURCHASED_FROM_REFERRAL = 'coursePurchasedFromReferral';
const COURSE_PURCHASED = 'coursePurchased';
const BANK_TRANSFER = 'bankTransfer';

const userCreditReasons = [
  SIGN_UP_BONUS,
  REGISTRATION_VERIFIED_FROM_REFERRAL,
  TRIAL_TAKEN_FROM_REFERRAL,
  COURSE_PURCHASED_FROM_REFERRAL,
  COURSE_PURCHASED,
  BANK_TRANSFER,
];

export {
  SIGN_UP_BONUS,
  REGISTRATION_VERIFIED_FROM_REFERRAL,
  TRIAL_TAKEN_FROM_REFERRAL,
  COURSE_PURCHASED,
  COURSE_PURCHASED_FROM_REFERRAL,
  BANK_TRANSFER,
  userCreditReasons,
};
