const customMutationString = `
   signUp ( input: SignUpInput ): UserToken,
   setUserPassword ( id: ID!, password: String! ): User,
   resetUserPassword ( id: ID!, oldPassword: String!, newPassword: String!  ): User,
   login ( input: LoginInput ): UserToken,
   socialLogin ( input: SocialLoginInput ): UserToken,
   signupExistingUser ( input: ExistingUserInput, stopOtpTrigger:Boolean ): UserToken,
   resendUserOTP ( id: ID!): User,
   sendForgotPasswordOTP (input: PhoneInput, email: String): BooleanResult,
   resendForgotPasswordOTP (input: PhoneInput, email: String): BooleanResult,
   validateForgotPasswordOTP (input: PhoneInput, phoneOtp: Int, email: String, emailOtp: Int): BooleanResult,
   finishForgotPassword (input: PhoneInput, phoneOtp: Int, email: String, emailOtp: Int, newPassword: String!): BooleanResult,
   sendForgotPasswordLink (email: String!): BooleanResult,
   resetPasswordFromForgotPasswordLink (newPassword: String!): BooleanResult,
   userCourseSyllabus (courseId: ID): UserCourseSyllabus,
   userTopicJourney ( topicId: ID!, courseId: ID): UserTopicJourney,
   userFirstAndLatestQuizReport ( topicId: ID!, courseId: ID): UserFirstAndLatestQuizReport,
   skipVideo ( topicId: ID!): SkipVideo,
   skipPracticeQuestion ( learningObjectiveId: ID!): BooleanResult,
   userBadge (courseId: ID): UserBadge,
   getUnlockedUserBadge ( input: GetUnlockedUserBadgeInput ): GetUnlockedUserBadgeResult,
   getQuizReport ( input: GetQuizReportInput): GetQuizReportResult,
   menteeCourseSyllabus (courseId: ID): MenteeCourseSyllabus,
   tcirtSdrowssaPtes ( id: ID!, password: String! ): User,
   uploadFile (fileInput: FileInput, connectInput: FileConnectInput): File! ,
   parentChildSignUp ( schoolId: ID, campaignId: ID, input: ParentChildSignUpInput ): ParentChildToken,
   updateParentChildDetail ( userId:ID!, schoolId: ID, input: UpdateParentChildDetailInput ): ParentChildToken,
   signUpAffiliate ( input: SignUpAffiliateInput ): UserToken,
   signUpSchool ( schoolId: ID!, input: SignUpAffiliateInput ): UserToken,
   loginViaPassword ( input: EmailLoginInput ): ParentChildToken,
   loginViaOtp ( input: ExistingUserInput ): BooleanResult,
   signupOrLoginViaOtp ( input: SignupOrLoginUserInput ): BooleanResult,
   validateUserOTP ( input: ValidateUserInput  ): ParentChildToken,
   getPaymentRequest ( productId: ID!, discountCode: String, isCreditUsed: Boolean): PaymentRequest,
   getPaymentResponse ( id: ID!, hash: String!, status: String!, payuMoneyId: String!): BooleanResult,
   addUpdateBulkSchoolUserData (sheetId: String!, schoolName: String!, setPassword: Boolean, booking: Boolean): AddUpdateBulkSchoolUserDataOutput,
   updateVisitorReactionOnUserApprovedCode(reactedByID: ID!, userApprovedCodeID: ID!, heart: Boolean, celebrate: Boolean, hot: Boolean): BooleanResult,
   addBulkMentorSession ( input: BulkMentorSessionInput ): [MentorSession],
   bookB2B2CSlots ( input: BookB2B2CSlotsInput ): BooleanResult, 
   rebookMenteeSession ( input: RebookMenteeSessionInput ): MenteeSession,
   sendJourneySnapshotInMail ( input: SendJourneySnapshotInMailInput ): BooleanResult,
   sendCertificateInMail ( input: SendCertificateInMailInput ): BooleanResult,
   `;

export default customMutationString;
