const customMutationString = `
   signUp ( input: SignUpInput ): UserToken,
   setUserPassword ( id: ID!, password: String! ): User,
   resetUserPassword ( id: ID!, oldPassword: String!, newPassword: String!  ): User,
   login ( input: LoginInput ): UserToken,
   socialLogin ( input: SocialLoginInput ): UserToken,
   signupExistingUser ( input: ExistingUserInput, stopOtpTrigger:Boolean ): UserToken,
   validateUserOTP ( id: ID!, phoneOtp: Int, emailOtp: Int ): User,
   resendUserOTP ( id: ID!): User,
   sendForgotPasswordOTP (input: PhoneInput, email: String): BooleanResult,
   resendForgotPasswordOTP (input: PhoneInput, email: String): BooleanResult,
   validateForgotPasswordOTP (input: PhoneInput, phoneOtp: Int, email: String, emailOtp: Int): BooleanResult,
   finishForgotPassword (input: PhoneInput, phoneOtp: Int, email: String, emailOtp: Int, newPassword: String!): BooleanResult,
   sendForgotPasswordLink (email: String!): BooleanResult,
   resetPasswordFromForgotPasswordLink (newPassword: String!): BooleanResult,
   userCourseSyllabus : UserCourseSyllabus,
   userTopicJourney ( topicId: ID!): UserTopicJourney,
   userFirstAndLatestQuizReport ( topicId: ID!): UserFirstAndLatestQuizReport,
   skipVideo ( topicId: ID!): SkipVideo,
   skipPracticeQuestion ( learningObjectiveId: ID!): BooleanResult,
   userBadge : UserBadge,
   getUnlockedUserBadge ( input: GetUnlockedUserBadgeInput ): GetUnlockedUserBadgeResult,
   getQuizReport ( input: GetQuizReportInput): GetQuizReportResult,
   menteeCourseSyllabus : MenteeCourseSyllabus,
   tcirtSdrowssaPtes ( id: ID!, password: String! ): User,
   uploadFile (fileInput: FileInput, connectInput: FileConnectInput): File! ,
   parentChildSignUp ( input: ParentChildSignUpInput ): UserToken,
   `;

export default customMutationString;
