const StudentsDraftCSV = `
  type StudentsDraftCSV {
    childName: String
    parentName: String
    rollNo: String
    grade: String
    section: String
    parentEmail: String
    status: String
    error: String
  }
`;

const DraftCSVConfig = `
  type DraftCSVConfig {
    title: String
    parentNameHeader: String
    rollNoHeader: String
    gradeHeader: String
    sectionHeader: String
    parentEmailHeader: String
    studentNameHeader: String
  }
`;

const School = `
  type School @model {
    name: String! @unique
    code: String @unique @trim @lowercase
    whiteLabel: Boolean @defaultValue(value: "false")
    admins: [User] @relation(name:"UserSchool")
    enrollmentType: EnrollmentType! @defaultValue(value: "free")
    classes: [SchoolClass] @relation(name: "SchoolClassSchool")
    students: [StudentProfile] @relation(name: "StudentProfileSchool")
    bde: BDEProfile @relation(name: "BDEProfileSchool")
    coordinatorEmail: String @uniqueOrEmpty @trim
    coordinatorPhone: Phone @uniqueOrEmpty
    coordinatorRole: SchoolCoordinatorRole
    coordinatorName: String
    city: String
    country: Country @defaultValue(value: "india")
    products: [Product] @relation(name: "SchoolProduct")
    logo: File @relation(name: "SchoolLogo", direction: "OneWay")
    schoolPicture: File @relation(name: "SchoolPicture", direction: "OneWay")
    hubspotId: String
    schoolCampaignCode: String @unique @trim
    isWhatsAppCommsEnabled: Boolean @defaultValue(value: "false")
    isEmailCommsEnabled: Boolean @defaultValue(value: "false")
    isTeachersAppEnabled: Boolean @defaultValue(value: "false")
    isOtpLoginEnabled: Boolean @defaultValue(value: "false")
    timetableSchedule: [TimetableSchedule] @relation(name: "SchoolTimetableSchedule")
    teachers: [MentorProfile] @relation(name: "MentorProfileSchool")
    isBuddyLoginEnabled: Boolean @defaultValue(value: "false")
    buddyLoginLimit: Int @defaultValue(value: "5")
    isTimeTableEnabled: Boolean @defaultValue(value: "false")
    isClassroomEnabled: Boolean @defaultValue(value: "true")
    studentsDraftCSVConfig: DraftCSVConfig
    studentsDraftCSV: [StudentsDraftCSV]
    studentsUploadStatus: BatchCreationStatus @defaultValue(value: "todo")
    isOtpAutoGenerated: Boolean @defaultValue(value: "false")
  }
`;
export default [School, StudentsDraftCSV, DraftCSVConfig];
