const SECRET = process.env.SECRET || 'default_jwt_secret_change_in_production';
const FORGOT_PASSWORD_SECRET = process.env.FORGOT_PASSWORD_SECRET || 'default_forgot_pwd_secret';
const LINK_TOKEN_SECRET = process.env.LINK_TOKEN_SECRET || 'default_link_token_secret';

const coreAuthParams = {
  SECRET,
  FORGOT_PASSWORD_SECRET,
  TOKEN_EXPIRY_DATE: '1y',
  FORGOT_PASSWORD_EXPIRY_DATE: '1h',
  FRONTEND_STATIC_APP_TOKEN_EXPIRY_DATE: '10y',
  BACKEND_STATIC_APP_TOKEN_EXPIRY_DATE: '10y',
  SUPER_ADMIN_TOKEN_EXPIRY_DATE: '2h',
  ADMIN_TOKEN_EXPIRY_DATE: '30d',
  USER_SIGN_UP_EXPIRY_DATE: '1y',
  ALGORITHM: 'HS256',
  SALT: 12,
  OTP_EXPIRATION_TIME_IN_SEC: 300,
  LINK_TOKEN_SECRET,
  DEFAULT_EXPIRY_TOKEN_TIME_IN_HOUR: 24,
  DEFAULT_EXPIRY_TOKEN_TIME_IN_HOUR_FOR_WEB: 1,
};

export default coreAuthParams;
