import {
  UserTokenNotRequiredError, UnknownUserError, OTPMismatchError,
  PasswordMismatchError, UnauthenticatedUserError,
  UnauthenticatedAppError, AlreadyActiveUser,
  UserPasswordNotSetError, UserPasswordAlreadySetError,
  AppTokenNotRequiredError,
  InvalidApplicationNameError,
  InvalidStaticToken,
  MandatoryFieldNotSetError,
} from './auth';

import {
  DatabaseRecordNotFoundError,
  ConnectRecordsNotFoundInDBError,
  UserAlreadyExistsError,
  AdditionalFieldUpdateDeniedError,
  FileWriteError,
  ChapterIsPublishedError,
  TopicIsPublishedError,
  VideoIsPublishedError,
  LearningObjectiveIsPublishedError,
  QuestionIsPublishedError,
  MessageIsPublishedError,
} from './db';
import {
  RelationValuesExistError, ConnectMutationsArgumentsLimitError,
  OneToOneRelationSentInInputAndAsConnectError, RelationMutationSimilarTypeArgumentError,
  MultipleArrayOperationDeniedError, InvalidArrayUpdateOperationError,
} from './mutations';

import { FileUploadError,
  InvalidFileUploadSizeError,
  InvalidFileUploadExtensionError,
  InvalidFileUploadSizeAndExtensionError,
  FileUsageCountNotZeroError,
  FileIdIsMandatoryError,
} from './files';
import { InvalidWriteAccessError, InvalidReadAccessError, InvalidActionOnDefaultFieldsError,
  UnauthorizedOperationError, BlockedOperationError, PermissionDeniedError,
  UserRolesNotFoundError } from './permissions';

import { InvalidSortFieldError, InvalidFilterArgumentsError, NotFilterRequiredError,
  InvalidParamsError, ConnectionAlreadyExistError, ConnectionNotExistError,
  FetchError, InvalidFieldType } from './queries';
import {
  NestingLevelExceedingError, BiDirectionalRelationsRequiredError, NoUniqueFieldError,
  RelationAppliedOnSameFieldsError, RemoteRelationError, DefaultDirectiveAppliedOnWrongFieldError,
  InvalidDateFormatError,
  UnsupportedListFieldInsideSubDocumentObjectError,
} from './types';
import { EitherEmailOrPhoneRequiredError, InvalidEmailError, InvalidPhoneError,
  EitherUsernameEmailOrPhoneRequiredError, InvalidNameError, InvalidNameLengthError,
  InvalidUsernameError, InvalidUsernameLengthError, EitherEmailOrPhoneNotBothRequiredError,
  PhoneNumberAndCountryCodeRequiredError, EitherPhoneOrEmailOtpRequiredError,
  EmailNotVerifiedError, PhoneNotVerifiedError,
  ConnectIdsArleadyRelatedError,
} from './input';


// assessment validation sqs  profile apolloErrorPackageTest maxSync transcoder
export {
  UserTokenNotRequiredError,
  UnknownUserError,
  PasswordMismatchError,
  UnauthenticatedUserError,
  UnauthenticatedAppError,
  FetchError,
  FileWriteError,
  FileUploadError,
  RelationValuesExistError,
  ConnectMutationsArgumentsLimitError,
  OneToOneRelationSentInInputAndAsConnectError,
  InvalidWriteAccessError,
  InvalidReadAccessError,
  InvalidActionOnDefaultFieldsError,
  UnauthorizedOperationError,
  BlockedOperationError,
  InvalidSortFieldError,
  InvalidFilterArgumentsError,
  NotFilterRequiredError,
  InvalidParamsError,
  NestingLevelExceedingError,
  BiDirectionalRelationsRequiredError,
  NoUniqueFieldError,
  RelationAppliedOnSameFieldsError,
  RemoteRelationError,
  DefaultDirectiveAppliedOnWrongFieldError,
  EitherEmailOrPhoneRequiredError,
  InvalidEmailError,
  InvalidPhoneError,
  EitherUsernameEmailOrPhoneRequiredError,
  InvalidNameError,
  InvalidNameLengthError,
  InvalidUsernameError,
  InvalidUsernameLengthError,
  OTPMismatchError,
  AlreadyActiveUser,
  EitherEmailOrPhoneNotBothRequiredError,
  UserPasswordNotSetError,
  UserPasswordAlreadySetError,
  PhoneNumberAndCountryCodeRequiredError,
  RelationMutationSimilarTypeArgumentError,
  PermissionDeniedError,
  AppTokenNotRequiredError,
  InvalidApplicationNameError,
  InvalidStaticToken,
  ConnectionAlreadyExistError,
  ConnectionNotExistError,
  EitherPhoneOrEmailOtpRequiredError,
  InvalidFileUploadSizeError,
  InvalidFileUploadExtensionError,
  InvalidFileUploadSizeAndExtensionError,
  InvalidFieldType,
  ConnectIdsArleadyRelatedError,
  FileUsageCountNotZeroError,
  PhoneNotVerifiedError,
  EmailNotVerifiedError,
  MandatoryFieldNotSetError,
  AdditionalFieldUpdateDeniedError,
  UserRolesNotFoundError,
  InvalidDateFormatError,
  MultipleArrayOperationDeniedError,
  InvalidArrayUpdateOperationError,
  DatabaseRecordNotFoundError,
  ConnectRecordsNotFoundInDBError,
  UserAlreadyExistsError,
  ChapterIsPublishedError,
  TopicIsPublishedError,
  VideoIsPublishedError,
  LearningObjectiveIsPublishedError,
  QuestionIsPublishedError,
  MessageIsPublishedError,
  FileIdIsMandatoryError,
  UnsupportedListFieldInsideSubDocumentObjectError,
};
