const directive = `
# Slugifies a string input, args: name, direction, fields
directive @relation(name: String!) on FIELD

# Uppercases a string
directive @upperCase on FIELD

# declares a field as unique
directive @unique on FIELD

# declares a field as unique but not mandatory
directive @uniqueOrEmpty on FIELD

# model declaration for type
directive @model on SCHEMA

# field value come from a remote source
directive @remote on FIELD

# field can only be fetched and not written
directive @readOnly on FIELD

# field can only be written and not fetched
directive @writeOnly on FIELD

# default value of the field will be put in database
directive @defaultValue on FIELD

# to define a additional field in type schema
directive @isRelationField on FIELD

# field value can be autoGenerated
directive @auto on FIELD

# field on which the groupBy query need to be applied
directive @groupBy on FIELD

# relational field where count can be fetched using filters
directive @relationalMeta on FIELD

# cache control
directive @cacheControl(
  maxAge: Int
  scope: CacheControlScope
  inheritMaxAge: Boolean
) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION
`;

export default directive;
