const directive = `
# Permission input type for RBAC directives
input PermissionInput {
  operations: String
  userRole: [String]
  appName: String
}

enum PermissionRule {
  allow
  deny
}

# Defines relations between types
directive @relation(
  name: String
  direction: String
  isSubset: Boolean
  fields: [String]
) on FIELD_DEFINITION | FIELD

# Uppercases a string
directive @upperCase on FIELD_DEFINITION | FIELD

# Declares a field as unique
directive @unique on FIELD_DEFINITION | FIELD

# Declares a field as unique but not mandatory
directive @uniqueOrEmpty on FIELD_DEFINITION | FIELD

# Model declaration for type
directive @model(
  database: DatabaseDialect
  secondaryApplications: [String]
) on OBJECT | SCHEMA

# Field value comes from a remote source
directive @remote on FIELD_DEFINITION | FIELD

# Field can only be fetched and not written
directive @readOnly on FIELD_DEFINITION | FIELD

# Field can only be written and not fetched
directive @writeOnly on FIELD_DEFINITION | FIELD

# Default value of the field
directive @defaultValue(
  value: String
) on FIELD_DEFINITION | FIELD

# Defines additional relation field in type schema
directive @isRelationField on FIELD_DEFINITION | FIELD

# Field value can be autoGenerated
directive @auto on FIELD_DEFINITION | FIELD

# Enables groupBy aggregation query on field
directive @groupBy on FIELD_DEFINITION | FIELD

# Relational field where count can be fetched using filters
directive @relationalMeta on FIELD_DEFINITION | FIELD

# Trims whitespace
directive @trim on FIELD_DEFINITION | FIELD

# Disables filter on field
directive @filterOff on FIELD_DEFINITION | FIELD

# Namecases a string
directive @nameCase on FIELD_DEFINITION | FIELD

# Role-Based Access Control (RBAC) permissions
directive @userPermissions(
  permissions: [PermissionInput]
  rule: PermissionRule
  crud: [String]
  read: [String]
  create: [String]
  update: [String]
  delete: [String]
  exceptRead: [String]
  exceptCreate: [String]
  exceptUpdate: [String]
  exceptDelete: [String]
) on OBJECT | FIELD_DEFINITION | FIELD

# App-level permissions
directive @appPermissions(
  permissions: [PermissionInput]
  rule: PermissionRule
  read: [String]
  write: [String]
) on OBJECT | FIELD_DEFINITION | FIELD

# Cache control for CDN and Redis
directive @cacheControl(
  maxAge: Int
  scope: CacheControlScope
  inheritMaxAge: Boolean
) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

# Create index for a field
directive @createIndex(
  value: Int
  order: Int
) on FIELD_DEFINITION | FIELD

# Define controller mode for querying database
directive @databaseController(
  mode: DatabaseControllerMode
) on OBJECT | SCHEMA | FIELD_DEFINITION | FIELD

# Clamp Integer/Float to minimum or maximum value
directive @clamp(
  min: Float
  max: Float
) on FIELD_DEFINITION | FIELD

# History model tracking
directive @history on OBJECT | FIELD_DEFINITION
directive @historyModel on OBJECT | FIELD_DEFINITION

# Declarative Multi-Tenancy & Row-Level Security
directive @tenantScoped(
  field: String
  claim: String
) on OBJECT

directive @ownerScoped(
  field: String
  claim: String
) on OBJECT
`;

export default directive;
