const directive = `
# Slugifies a string input, args: name, direction, fields
directive @relation(name: String!, direction: String, isSubset: Boolean) on FIELD | FIELD_DEFINITION

# Uppercases a string
directive @upperCase on FIELD | FIELD_DEFINITION

# declares a field as unique
directive @unique on FIELD | FIELD_DEFINITION

# declares a field as unique but not mandatory
directive @uniqueOrEmpty on FIELD | FIELD_DEFINITION

# model declaration for type
directive @model on OBJECT | FIELD_DEFINITION | SCHEMA

# field value come from a remote source
directive @remote on FIELD | FIELD_DEFINITION 

# field can only be fetched and not written
directive @readOnly on FIELD | FIELD_DEFINITION

# field can only be written and not fetched
directive @writeOnly on FIELD | FIELD_DEFINITION

# default value of the field will be put in database
directive @defaultValue(value: String) on FIELD | FIELD_DEFINITION

# to define a additional field in type schema
directive @isRelationField on FIELD | FIELD_DEFINITION

# field value can be autoGenerated
directive @auto on FIELD | FIELD_DEFINITION

# field on which the groupBy query need to be applied
directive @groupBy on FIELD | FIELD_DEFINITION

# relational field where count can be fetched using filters
directive @relationalMeta on FIELD | FIELD_DEFINITION

# trim
directive @trim on FIELD | FIELD_DEFINITION

# filterOff
directive @filterOff on FIELD | FIELD_DEFINITION

# value
directive @value on FIELD | FIELD_DEFINITION

# length
directive @length(min:String, max:String) on FIELD | FIELD_DEFINITION
`;

export default directive;
