import { DataTypes } from 'sequelize';
import cuid from 'cuid';
import db from '../../../db';

const { sequelize } = db;

const UserLevelSessionReport = sequelize.define(
  'UserLevelSessionReport',
  {
    id: {
      type: DataTypes.STRING,
      defaultValue: cuid(),
      primaryKey: true,
    },
    userId: { type: DataTypes.STRING, allowNull: false },
    userName: { type: DataTypes.STRING, allowNull: false },
    userRole: { type: DataTypes.STRING, allowNull: false },
    studentGrade: { type: DataTypes.STRING, allowNull: true },
    studentSection: { type: DataTypes.STRING, allowNull: true },
    classroomId: { type: DataTypes.STRING, allowNull: true },
    classroomTitle: { type: DataTypes.TEXT, allowNull: true },
    schoolId: { type: DataTypes.STRING, allowNull: true },
    schoolName: { type: DataTypes.TEXT, allowNull: true },
    topicId: { type: DataTypes.STRING, allowNull: false },
    sessionId: { type: DataTypes.STRING, allowNull: true },
    sessionTitle: { type: DataTypes.TEXT, allowNull: false },
    sessionType: { type: DataTypes.TEXT, allowNull: false },
    courseId: { type: DataTypes.STRING },
    courseTitle: { type: DataTypes.TEXT },
    courseCategory: { type: DataTypes.TEXT },
    sessionStart: { type: DataTypes.DATE, allowNull: true },
    sessionEnd: { type: DataTypes.DATE, allowNull: true },
    sessionCreationDate: { type: DataTypes.DATE, allowNull: true },
    sessionUpdationAt: { type: DataTypes.DATE, allowNull: true },
    sessionDuration: { type: DataTypes.INTEGER, allowNull: true },
    sessionStatus: { type: DataTypes.STRING, allowNull: true },
    studentAttendance: { type: DataTypes.BOOLEAN },
    classroomStudentsCount: { type: DataTypes.INTEGER },
    teacherTaughtName: { type: DataTypes.STRING },
    teacherTaughtId: { type: DataTypes.STRING },
    sessionClassworkComponents: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    sessionHomeworkComponents: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    classworkVisited: { type: DataTypes.INTEGER, allowNull: false },
    classworkAttempted: { type: DataTypes.INTEGER, allowNull: false },
    homeworkVisited: { type: DataTypes.INTEGER, allowNull: false },
    homeworkAttempted: { type: DataTypes.INTEGER, allowNull: false },
    classworkScore: { type: DataTypes.INTEGER, allowNull: false },
    homeworkScore: { type: DataTypes.INTEGER, allowNull: false },
    proficiency: { type: DataTypes.INTEGER, allowNull: false },
    homeworkExists: { type: DataTypes.BOOLEAN },
    videoComponentLog: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    pqComponentLog: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    classworkAssignmentLog: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    homeworkAssignmentLog: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    classworkPracticeLog: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    homeworkPracticeLog: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    classworkProjectLog: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    homeworkQuizLog: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    previousLogs: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    videosCount: { type: DataTypes.INTEGER, allowNull: true },
    videosVisitedCount: { type: DataTypes.INTEGER, allowNull: true },
    videosVisitedPercent: { type: DataTypes.INTEGER, allowNull: true },
    practiceQuestionsCount: { type: DataTypes.INTEGER, allowNull: true },
    practiceQuestionsAttemptedCount: { type: DataTypes.INTEGER, allowNull: true },
    practiceQuestionsAttemptedPercent: { type: DataTypes.INTEGER, allowNull: true },
    latestPracticeQuestionTriesLoWise: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    latestPracticeQuestionTriesSessionWise: { type: DataTypes.ARRAY(DataTypes.JSONB) },
    averageCorrectPracticeQuestionTries: { type: DataTypes.DOUBLE, allowNull: true },
    codingAssignmentsCount: { type: DataTypes.INTEGER, allowNull: true },
    codingAssignmentsAttemptedCount: { type: DataTypes.INTEGER, allowNull: true },
    codingAssignmentsAttemptedPercent: { type: DataTypes.INTEGER, allowNull: true },
    practicesCount: { type: DataTypes.INTEGER, allowNull: true },
    practicesAttemptedCount: { type: DataTypes.INTEGER, allowNull: true },
    practicesAttemptedPercent: { type: DataTypes.INTEGER, allowNull: true },
  },
  {
    sequelize,
    isPgModel: true,
    tableName: 'userLevelSessionReport',
    modelName: 'UserLevelSessionReport',
  },
);

export default UserLevelSessionReport;
