name: tekie-backend-staging

on:
  push:
    branches:
      - master-staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: Delete Old Artifacts
        uses: actions/github-script@v6
        id: artifact
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            res.data.artifacts
              .filter(({ name }) => name === 'node-app')
              .forEach(({ id }) => {
                github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: id,
                })
              })

      - name: npm install, build.
        env:
          NODE_ENV: staging
          NPM_CONFIG_PRODUCTION: false
          APPLICATION: core
          GSUIT_CONFIGURATION: eyJ0eXBlIjoic2VydmljZV9hY2NvdW50IiwicHJvamVjdF9pZCI6InRla2llLXRlc3QiLCJwcml2YXRlX2tleV9pZCI6IjdkY2RiMmE4YTI2NGQ1ZGMxNzU3OTc0MDgyNzk3NzI3NWM0ZGRhYTYiLCJwcml2YXRlX2tleSI6Ii0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFETXVQS2xzdzZBWmtTeVxuVXBSNFRacjNLSFRzdURFMXpvdXB6aVFrUW9hTHpsdXZuQXFrMnpJUExlNTByb3BRL2c1TE4zV1NhaTBab3Y3QVxubDdaUnB4WEpCVk5HSUhyNHErRWZhV2NNWWJoekdUWHN4MmRlSnJVWjZ3cElrVTFZdlFDQ3J0QVAyT2ttWFQ0UVxuaDdQOXQvKy9LTEZzb0c1WkhTbnNOZmxjQkJkU002VGRHQ2Urd1VMK0pnV2lkU2QwdWduUEdyVVhHUytVSkVJcVxuRW9zL0JDVUI0dDlTdzV3SjIwN3JNMDQ0VVlVaExPZmp5a3JicDI5Z2FBZVpUZWhVdzhPU3BnbnBBYm5LK2V5VVxuakk4VU9rbU9qQ0loZUozTGtoWTgrdlRyK0lvbGdiaXRORWxOQnVUelZlWDkyN1BCejFlTnNESmI0YzM5QnhSRFxud1JodDVYajdBZ01CQUFFQ2dnRUFMOVVzdUtPQUNXY2J1UENMaVJwVTBWZk9EZnN4WUVtTW4xV3ZZeHQ2RlZOWFxuWDg0ZFBJeU1nemh2cFNxYzNiU21nVk9KY0hiSFo5eUtHbFM0UUJiQ2c4L3ZONHppUHBUbVNqRVY1ekl6NXd5bVxuYVZiajQzODJ4RUlEQ3BhTWxHWEFwMGdTREFuWjIrRmdYWHRmaGpJR0d0TjJ0Uk05QlN4SHZjMlVvRGZDZlMxeFxuNW9aVk9SK042V3ZSMHk1RFJuZVlYOWlnTHphNmMzbVBuSWhVR2F5WXQvR3pKaVp3Q1VIY2RBY3k0UzkxWGIvYVxuNzUwQTRveUJ3dFNQUzNHT3NIVWRFdkxHYzZPUmVwQjBZdGl2TkJrSkRObGpXRG1wR1hMRkFFNWUyYm9XdWtBOVxuTjJYc1R0c3BFTi8vWFkrZHM3QUpLUE1OV0hZWFJmOGVXUFppMHF4OGdRS0JnUURsbHNRNWRRY2RxN0plYnMvelxualEzaWRUNXFjajNJSlFWUFBZVks0anZsZ0dFbUJKNk9GelNpUFpJVGdwU2hKVXN3TUhVeEhGQzM0S3hkVjFwZVxuZGZ5bmltVmR2eDFXYjNmVDA4YmxSeG4yVXRDQzM1bjhISWxMQmw5cVdpS1l2Y0hqaENiVlIxWFd2MUNSanJjbFxuMk9IN1VoUUg4WUp4OVRoMTlaWnhIZXJtZ1FLQmdRRGtSZUdEdDYzZnVWTUtNeFZ6V3c1enRwQlpEdEhMN0w0VVxuelY5OXM3c3RGT0ZvN1FTWHVIMVZ1REY2R1h0NnBYZ1lvRE1EQ040d1c5ZDdlc1ZyTVJnTkN3NHprUyt0Wkh5d1xuYXNGRCtTellQeUMwMndTbTduVXB3U0UzL3Z1TEdaTW5ReEJpUXoybVg0bWtzSS9qNVUyK2hUZXFxWEdQMXRsalxuT3NrL1liWTVld0tCZ0V6NXlKNlBDeXk2aFZvK0F3RGdlUmhGUVFFRmZvdGRSak4wSi8yY2JvS2JFWGRpc3hwbVxuMDJIV0RPVDNzZ2Q1Ym9VZ3Fob21LVFlOWVIwR2pha0FIQTY4U3hJc1lwUzVXTTZ2d1k3YjBPdVNocEJxa2NGQ1xuZkJHb2VGTTdGMEJvMXRvR1U5TE1VUTVvSklZNCtGVDdLNEZNMnFSeko4NDNibysySUpPYWVVaUJBb0dBUWpYbVxudUc3UmR2L3BEeDlNREg2UHpZNVpoZ3RmWE5mWk5tMXZVaVdNbUFIamM2eXoxVklFd0pWQmZKbmhqK3hvempQQlxuT0JNZFowZHNVL3VEUVprbTBibXdMOUxmMGxwQU5HZHlrVVczOVMweVRtTHNrWUsrNXhLR2tSaGJXN2hhVDF3TFxuWjRUN1g4TjhTQkdTV3RiSzJ3VUc1WEJxYVA4M1pLbkxiNS9tMi9zQ2dZRUF3TWVPSXBsdDJoMDFxMUtRWkFXblxuVEhBejFWUVFsM1dHd2JSTG1KQ0hyUFJRbXh5QTFsYk53ZnlOVi9uVk1VblBzZ2RKOVlEWmE1anhIMklla3k2SVxuaE54eVBpYTQyenowZmd4UnluWDdraGhZcllhT0E1ckVZR1BRMFByejg2akMyc1NMbzBZUk4wckhhZ2Q0NEhDM1xuMTZ3bjI2bkJsV2hFa1ZyQ1V4N3Z0M1U9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLCJjbGllbnRfZW1haWwiOiJ0ZWtpZS0yOTNAdGVraWUtdGVzdC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsImNsaWVudF9pZCI6IjExNDg5NjE2MDg5NjM2NTQxMzgxMyIsImF1dGhfdXJpIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLCJ0b2tlbl91cmkiOiJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsImNsaWVudF94NTA5X2NlcnRfdXJsIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS90ZWtpZS0yOTMlNDB0ZWtpZS10ZXN0LmlhbS5nc2VydmljZWFjY291bnQuY29tIn0=
        run: |
          npm install
          npm run build:cloudProd

      - name: Zip artifact for deployment
        run: zip build.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip build.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tekie-backend-staging'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CAFBCE53FD4B4F3780A89822454BA7F2 }}
          package: .
